### ISSUE TITLE
React Dependency in Podspec Installs Obsolete React 0.11, Breaks Build for Projects

### ISSUE THREAD

**Issue by huntharo** [ocetnik/react-native-background-timer#71] opened 2018-01-23 17:27 UTC
Hi There!  Thanks for working on your project and making it available as open source!

In trying to use the project I've run into an issue that's become rather common which is that the React dependency in the podspec causes React 0.11 to be installed which then breaks the build for apps that are using a different version of React (and React is no longer provided by Pod, it seems).

The Firebase project encountered this same issue here and decided to remove the dependency from the podspec (see comment right above the pull reference):
https://github.com/invertase/react-native-firebase/issues/324#ref-pullrequest-249294356

They removed the React dependency here:
https://github.com/invertase/react-native-firebase/pull/325

What are your thoughts on this?

**Comment by ocetnik** [comment] 2018-03-01 10:18
Released in v2.0.1

**Closed by ocetnik** 2018-03-01 10:18 UTC

**Comment by jgreen210** [comment] 2018-05-08 15:45
Removing the React dependency from the podspec is causing https://github.com/ocetnik/react-native-background-timer/issues/82. 

https://github.com/invertase/react-native-firebase/pull/325 was never merged into the react-native-firebase master branch, so it still has React in its podspec file:

https://github.com/invertase/react-native-firebase/blob/v4.1.0/ios/RNFirebase.podspec

So, I wonder if cocoapods 1.5.0 solves this issue too, without the need to remove the React dependency?

**Comment by jgreen210** [comment] 2018-05-08 16:05
This issue's description says "React is no longer provided by Pod, it seems". That's true, but it makes me wonder if this issue was caused by something in @huntharo's Podfile. Here:

https://facebook.github.io/react-native/docs/integration-with-existing-apps.html

...the React pod is set up using relative paths that point to files managed by npm/yarn, so you should just get whatever version is specified in the package.json and/or the npm/yarn lock/shrinkwrap file, even if other pods also declare a dependency on the React pod.

**Comment by huntharo** [comment] 2018-05-08 16:17
Here are my current observations:

- Regarding #82 - Is it really RCTBridge.h not found or is it RCTBridgeModule.h not found?  What I find odd about RNBackgroundTimer.h is that it uses two different styles (quotes and angle brackets and one has React in the path but the other does not) for includes of React headers.  I have previously had to change them both to one consistent pattern to work around this but for some reason it's not causing me problems at the moment.  I think fixing the includes to be consistent will resolve #82.
- My own Podspec was previously empty except for HockeySDK.  Unfortunately, I started using react-native-sqlite-storage and it is easiest to include via a Podspec reference but it ends up needing React to be included via the Podspec as well.  To address this I added the contents below to my Podspec; previously my Podspec was empty other than HockeySDK.  I think this can work for other packages that need React in the Podspec.  Overall I'm not sure where to go with this (e.g. either all packages should attempt to not need React in their Podspec as a dependency or all packages should have it and every consuming project will need something like the following in their top-level Podspec).

```
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [ 'Core',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTBlob' ]
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
```

**Comment by jgreen210** [comment] 2018-05-08 16:33
You're right, it was RCTBridgeModule.h not RCTBridge.h. I've updated my comment in #82.

**Comment by jgreen210** [comment] 2018-05-08 16:54
https://medium.com/@joshyhargreaves/adding-react-native-to-existing-ios-project-without-cocoapods-6f1ee9106009
https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d
https://github.com/facebook/react-native/commit/59407f36608f52d4402d742d916f78acd3ca7152

Is the "copy headers" comment in the first link why "I have previously had to change them both to one consistent pattern to work around this but for some reason it's not causing me problems at the moment"?

**Comment by huntharo** [comment] 2018-05-08 17:46
@jgreen210 - I don't *believe* so as that says that issue has been resolved since RN 0.40+, but I started using RN around June/July of 2017, so I've always used version 0.44+.  However, I may have been linking against react-native-background-timer by just including the .h/.m files in my xcodeproj initially while later I switched to linking react-native-background-timer's xcodeproj into my xcodeproj, so it's possible that a setting similar to that referenced above may have fixed this when I started including the xcodeproj file.

**Comment by mjgallag** [comment] 2018-06-15 03:56
This fix in `2.0.1` breaks iOS build for ReactNative `0.55.4` and CocoaPods `1.5.3`, when I revert to `2.0.0` the build succeeds.

**Comment by kyungjoongo** [comment] 2018-10-17 01:11
> This fix in `2.0.1` breaks iOS build for ReactNative `0.55.4` and CocoaPods `1.5.3`, when I revert to `2.0.0` the build succeeds.

Downgrading to 2.0.0 works well.

**Comment by pencilcheck** [comment] 2019-01-17 00:11
Upgrade to 2.1.1 seems to fix this issue as well.

**Comment by nicholascm90** [comment] 2019-02-26 19:43
@pencilcheck I had this issue when installing 2.1.1 (0.11 installed for React)

**Comment by octopusbaba** [comment] 2019-03-03 17:03
How to get rid of this issue ? still not getting the way out of this ??
